a = int(input("Enter thye value of a:"))
b = int(input("Enter the value of b:"))
c = int(input("Enter the value of c:"))
d = int(input("Enter the value of d:"))
print("a is greater than b is:",a>b)
print("a is less than b is:",a<b)
print("a is equal to b is:",a==b)
print("a is not equal to b is:",a!=b)
print("b is greater then c is:",b>c)
print("b is less than c is:",b<c)
print("b is equal to c is:",b==c)
print("b is not equal to c is:",b!=c)
print("c is greater than d is:",c>d)
print("c is less than d is:",c<d)
print("c is equal to d is:",c==d)
print("c is not equal to d is:",c!=d)
print("d is greater than a is:",d>a)
print("d is less than a is:",d<a)
print("d is equal to a is:",d==a)
print("d is not equal to a is:",d!=a)